// <auto-generated />
namespace ICEP_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model));
        
        string IMigrationMetadata.Id
        {
            get { return "202111220801128_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
